### ISSUE TITLE
Invalid Directory Issuew

### ISSUE THREAD

**Issue by BlackVick** [wwdablu/wZip#1]
Hello. 
Please could you update library so that it creates directory if not exist? 
Thank you.

**Comment by wwdablu** [comment]
@BlackVick Request you to pull the changes from master or use 1.1.1 version and see if that works for you.
https://github.com/wwdablu/wZip/releases/tag/1.1.1

You can use gradle as:
implementation 'com.github.wwdablu:wZip:1.1.1'

**Comment by BlackVick** [comment]
Thanks a bunch sir. It worked great.
